version = 0.1
[default.deploy.parameters]
stack_name = "tekken-nuxt-3"
resolve_s3 = true
s3_prefix = "tekken-nuxt-3"
region = "us-west-2"
profile = "sambot"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
