AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    Tekken

    Sample SAM Template for Nuxt 3 server

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 8
        MemorySize: 128

Resources:
    NuxtGatewayApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: "v1"
    TekkenNuxt3ServerFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: .output/server/
            Handler: index.handler
            Runtime: nodejs18.x
            Architectures:
                - x86_64
            Description: Nuxt 3 SSR Lambda
            Events:
                Server:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /
                        Method: get
                        RestApiId:
                            Ref: NuxtGatewayApi

Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    TekkenNuxt3ServerApi:
        Description: "Endpoint to Nuxt 3 server"
        Value: !Sub "https://${NuxtGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/"
    TekkenNuxt3ServerFunction:
        Description: "Tekken Nuxt Server ARN"
        Value: !GetAtt TekkenNuxt3ServerFunction.Arn
    TekkenNuxt3ServerFunctionIamRole:
        Description: "Implicit IAM Role created for Tekken"
        Value: !GetAtt TekkenNuxt3ServerFunctionRole.Arn
